<section class="intro">
    <div class="container flex wrap">
        <div class="txt">
            <h2>DECOUVREZ SIMON, PROGRAMEUR INFORMATIQUE BIEN CAFEINE</h2>
            <p>Bonjour à vous et Bienvenu ! Je me permets, aujourd'hui, de vous présenter ma lettre de motivation. Je vous présente également mes excuses par avance pour avoir légèrement maltraité votre charte graphique. Complétant mon propre portfolio, je vais essayer de vous en dire un peu plus sur moi sans être redondant !</p>
            <p>Avant d'aller plus loin, vous trouverez dans le bloc du dessous la liste des projets que j'ai souhaité mettre en avant (les autres restants disponibles sur mon github ainsi que mon portfolio). Bonne lecture !</p>
            <a class="website" href="https://simonpatry.fr" target="_blank">Mon site</a>
        </div>
        <div class="animation flex wrap">
            <div class="responsive">
                <img id="circle1" src="assets\ressources\images\coffee_story.PNG" alt="CoffeeStory">
            </div>
            <img id="circle2" src="assets\ressources\images\compiling_coffee.gif" alt="compilingCoffee">
        </div>
    </div>
</section>

<section class="skills">
    <div class="container flex wrap">
        <h2>LE DEVELOPPEUR WEB TOUT-EN-UN: DEVENIR FULL STACK</h2>
        <div id="#projects" class="projects flex">
            <ul class="portfolio">
                <li>Portfolio: premier projet web mis en ligne</li>
                <li><a href="https://simonpatry.fr" target="_blank">lien direct</a></li>
                <li><a href="https://github.com/SimonPatry/portfolio" target="_blank">Github</a></li>
                <p id="ptext">HTML, CSS, JS, PHP, SQL l'ensemble des languages sont présents ici. Du design au dashboard j'ai réalisé ce site 100% en natif. Vous y retrouverez mon parcours ainsi que d'autres projets.</p>
            </ul>
            <ul class="doom">
                <li>Doom: Projet de fin de brache à 42</li>
                <li><a href="https://github.com/SimonPatry/Doom" target="_blank">Github</a></li>
                <p id="dtext">Mon plus gros projet: complètement fait main par un groupe de 3 personnes (aucune lib autorisée) des parseurs de son et d'images, au moteur graphique, à l'éditeur de maps 2D/3D en passant par la physique du jeu il contient grand nombre de challenges que ce soit de performance (multithreading), de compatibilité (mac, linux) et de choix (design, UX/UI)</p>
            </ul>
            <ul class="breaker">
                <li>Casse-briques</li>
                <li><a href="https://simonpat.sites.3wa.io/developpement/JS/exercices/js/JS2.2-StartArkanoid/index.html" target="_blank">lien de test</a></li>
                <li><a href="https://github.com/SimonPatry/Casse-briques" target="_blank">Github</a></li>
                <p id="btext">Casse brique basique en javascript issu d'un exercice de cours, une bonne partie du code de base donné (collisions, bonus) a été supprimé et recodé par mes soins</p>
            </ul>
        </div>
        <div class="course">
            <p>Parmi les éléments ne figurant nuls parts sur mon parcours: avant l'informatique, l'architecture était mon domaine. Un bac pro, complété par une MANAA puis une première année de BTS interrompue. Suite à cette interruption et après une période en intérim, j'ai réussi une piscine pour intégrer l'école 42 ! Avec un format d'apprentissage unique (pas d'enseignant ni de cours): un arbre de projets contenant avec domaines (graphisme, système, algo) et des délais pour seules étapes de formation. Ces délais additionnés au contexte du covid sont devenus incompatibles et mi-octobre 2020 l'aventure s'arrête.</p>
            <p>Je prends alors contact avec la 3W Academy en décembre puis commence finalement ma formation web en mars 2021. Celle-ci prend fin et moi voici finalement diplômé en tant que développeur intégrateur Web (bac +2) dont les résultats viennent d'arrivés il y a une semaine.</p>
            <p>Aujourd'hui, après plusieurs mois d'apprentissage en web je n'ai pas développé de "préférence" particulière pour le front ou le back, appréciant autant le front pour le design que le back pour la gestion des données mon objectif est de devenir fullstack, bien que plus performant en front pour le moment car plus proche en affinités naturelles c'est aujourd'hui le back que j'ai peut-être plus envie d'explorer aujourd'hui pour développer mes compétences.</p>
        </div>
    </div>
</section>

<section class="humanBeing">
    <div class="container flex wrap">    
        <h2>SIMON EST DIPLOME EN TANT QUE DEV/INTEGRATEUR WEB</h2>
        <div class="meImg">
            <img src="assets/ressources/images/me.png" alt="me">
        </div>
        <div class="meTxt">
            <p>Je voudrais vous parler ici de moi et de ma personnalité. N'appréciant guère l'austérité, je suis quelqu'un de joyeux et dynamique. J'aime quand les choses bougent autour de moi et suis toujours à l'affut d'un nouveau projet ou challenge. "Lassé" des cours aujourd'hui (tout du moins du manque de sens dans les exercices au quotidien) je cherche un environnement de travail dans lequel je pourrais m'épanouir en tant que dév au sein d'une équipe qui partage mes valeurs.</p>
            <p>Animé par une curiosité sans fin (comme l'histoire), je compte parmi mes inspirations des gens comme Alexandre Astier, François Rollin ou encore Bruce Benamran, des musiciens comme Paco de Lucia ou Al Di Meola. Ce sont des gens qui inspirent en moi une envie de devenir meilleurs dans ce que j'aime, à savoir le développement !</p>
        </div>
        <div class="meTxt">
            <p>Je me suis permis d'extraire ce témoignage de votre site, car ce témoignage correspond vraiment bien à mon regard sur le travail d'équipe, et à ma vision d'un métier de dév. Cette notion de travail en équipe fait partie de mes méthodes de travail depuis longtemps: l'architecture est un travail d'équipe, le développement est un travail bien ennuyeux tout seul.</p>
            <p>Comprenons-nous bien, je ne crains pas les tâches personnelles. Je parle plutôt d'une volonté de partager des objectifs, des idées et des valeurs avec un groupe où chacun apporte sa pierre (enfin son code) à l'édifice.</p>
        </div>
        <div class="meImg">
            <img src="assets/ressources/images/agreed.png" alt="me">
        </div>
    </div>
</section>

<section class="precious">
    <div class="container flex wrap">    
        <h2>ILS SONT A MOI</h2>
        <div class="wheel">
            <img id="pointer" src="assets/ressources/images/wheel_pointer.png" alt="pointer">
            <img id="wheel" src="assets/ressources/images/wheel.png" alt="lang">
        </div>
        <div class="language">
            <p id="wheelBtn" class="wheelBtn">tournez la roue</p>
            <p id="1">Je ne pense pas grand-chose de ce langage, n'ayant eu qu'un petit aperçu de ce pour quoi je le trouve utile - à savoir le SEO -, je ne peux pas dire que je l'apprécie ni le déteste. Je cherche en revanche de bonnes occasions de gagné en compétences sur le référencement, cet aspect du web étant extrêmement important.</p>
            <p id="2">Un "vieil ami", j'ai passé presque deux années de ma vie à coder en C, bien que j'aie acquis toutes les bases de la programmation avec, ce n'est pas un langage qui me manque pour autant. En revanche il reste, selon moi, le meilleur langage pour commencer à coder, appréhender la mémoire, les leaks et la propreté d'un code.</p>
            <p id="3">J'utilise le SQL pour faire des requêtes en bases de données, stocker/afficher des informations depuis la base ou encore des systèmes de connexion à un site avec un dashboard en tant qu'utilisateur ou administrateur.</p>
            <p id="4">Probablement langage que j'ai le moins utilisé, et donc celui que je maîtrise le moins selon le contexte, je pense avoir une bonne marge de progression en mvc/poo pour l'utilisation du php. Cependant c'est également là que je souhaite en apprendre le plus ! (en réalité, je souhaite en apprendre plus en backend, que ce soit php ou un autre language/framework)</p>
            <p id="5">Le moment amusant de ma journée, c'est le js ! c'est la partie contenant le plus d'algorithmie qui reste ma discipline préférée, dynamiser du front c'est toujours amusant et potentiellement challengeant. Mon expérience passée en C m'a également permis de prendre en main rapidement ce langage.</p>
            <p id="6">Cascading style sheets, un language que je trouve très long à mettre en place, mais qui fournit toujours un résultat à la auteur de nos attentes, couplé au JS je prends pas mal de plaisir à réalisé des maquettes pour du front avec.</p>
        </div>
    </div>
</section>