<section class="intro flex wrap">
    <div class="txt">
        <h2>DECOUVREZ SIMON, PROGRAMEUR INFORMATIQUE BIEN CAFEINE</h2>
        <p>Bonjour à vous et bienvenu ! Je me permet, aujourd'hui, de vous présenter ma lettre de motivation. Je vous présente également mes excuses par avance pour avoir légèrement maltraiter votre charte graphique. Complétant mon propre portfolio, je vais essayer de vous en dire un peu plus sur moi sans être redondant !</p>
        <p></p>
    </div>
    <div class="animation flex wrap">
        <img src="assets\ressources\images\compiling_coffee.gif" alt="compilingCoffee">
    </div>
</section>

<section class="humanBeing">
    <h2>Le développeur tout-en-un: devenir fullstack</h2>
</section>

<section class="skills">
    <h2>Simon est diplômé en tant que dév/intégrateur web</h2>
</section>