<section class="intro">
    <div class="container flex wrap">
        <div class="txt">
            <h2>DECOUVREZ SIMON, PROGRAMEUR INFORMATIQUE BIEN CAFEINE</h2>
            <p>Bonjour à vous et bienvenu ! Je me permet, aujourd'hui, de vous présenter ma lettre de motivation. Je vous présente également mes excuses par avance pour avoir légèrement maltraiter votre charte graphique. Complétant mon propre portfolio, je vais essayer de vous en dire un peu plus sur moi sans être redondant !</p>
            <p>Avant d'aller plus loin, voici la liste des projets que j'ai souhaiter mettre en avant (les autres restants disponible sur mon github ainsi que mon portfolio).</p>
            <ul>
                <li>Portfolio: premier projet web mis en ligne</li>
                <li><a href="https://simonpatry.fr">lien direct</a></li>
                <li><a href="https://github.com/SimonPatry/portfolio">Github</a></li>
            </ul>
            <ul>
                <li>Doom: Projet de fin de brache à 42</li>
                <li><a href="https://github.com/SimonPatry/Doom">Github</a></li>
            </ul>
            <ul>
                <li>Casse-briques</li>
                <li><a href="https://simonpat.sites.3wa.io/developpement/JS/exercices/js/JS2.2-StartArkanoid/index.html">lien de test</a></li>
                <li><a href="https://github.com/SimonPatry/Casse-briques">Github</a></li>
            </ul>
        </div>
        <div class="animation flex wrap">
            <img id="circle1" src="assets\ressources\images\coffee_story.PNG" alt="CoffeeStory">
            <img id="circle2" src="assets\ressources\images\compiling_coffee.gif" alt="compilingCoffee">
        </div>
    </div>
</section>

<section class="humanBeing">
    <div class="container">
        <h2>Le développeur tout-en-un: devenir fullstack</h2>
        <p>Parmis les éléments ne figurants nul parts sur mon parcours: avant l'informatique, l'architecture était mon domaine. Un bac pro, complété par une MANAA puis une première année de BTS interrompue. Suite à ctte interruption et après une période en intérim, j'ai réussi une piscine pour intégrer l'école 42 ! Avec un format d'apprentissage unique (pas d'enseignant ni de cours): un arbre de projets contenant avec domaines (graphisme, système, algo) et des délais pour seules étapes de formation. Ces délais additionnés au contexte du covid sont devenus incompatibles et mi octobre 2020 l'aventure s'arrête.</p>
        <p>Je prend alors contact avec la 3W Academy en décembre puis commence finalement ma formation web en mars 2021. Celle ci prend fin et moi voici finalement diplômé en tant que développeur intégrateur Web (bac +2) dont les résultats viennent d'arrivés il y a une semaine.</p>
    </div>
</section>

<section class="skills">
    <div class="container">    
        <h2>Simon est diplômé en tant que dév/intégrateur web</h2>
    </div>
</section>