<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8">
        <title>Candidature Simon PATRY</title>
        <meta name="description" content="Simon PATRY">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="assets/css/main.css" rel="stylesheet">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/fontawesome.min.css">
	    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/brands.min.css">
    	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/solid.min.css">
    </head>
    <body>
        <header class="flex wrap">
            <nav class="navbar flex wrap">
                <a class="nav-item" href="#top" ><img src="assets/ressources/images/logo.png" alt="candidature"></a>
                <div class="anchors flex wrap">
                    <a class="nav-item" href="#aboutMe">SIMON</a>
                    <a class="nav-item" href="#course">PROJETS</a>
                    <a class="nav-item" href="#code">LANGAGES</a>                   
                </div>
            </nav>
        </header>
        <main>
            <div class=" template flex wrap">
                <?php include $template ?>
            </div>
        </main>
        <footer>
            <div>
                <h2>ME CONTACTER</h2>
                <p>simonpatry12@gmail.com</p>
                <p>06 65 72 43 16</p>
                <p>11 passage du buisson saint louis, 75010 PARIS</p>
            </div>
        </footer>
    </body>
    
    <script src="assets/js/main.js"></script>
</html>