<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8">
        <title>CV simon</title>
        <meta name="description" content="Simon PATRY">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="assets/css/main.css" rel="stylesheet">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/fontawesome.min.css">
	    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/brands.min.css">
    	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/solid.min.css">
    </head>
    <body>
        <header class="flex wrap">
            <nav class="navbar">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a href="#top" class="nav-link" title="go top">
                            <i class="fas fa-chevron-circle-up fa-nav"></i>
                            <span class="link-text">UP</span>
                        </a>
                    </li>
                </ul>
            </nav>
        </header>
        <main>
            <div class=" template flex wrap">
                <?php include $template ?>
            </div>
        </main>
        <script src="assets/js/main.js"></script>
        <script src="assets/js/heroContainer.js"></script>
        <script src="assets/js/slider.js"></script>
    </body>
</html>